CREATE TABLE raffle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    unit_price_cents INTEGER CHECK (unit_price_cents IS NULL OR unit_price_cents > 0),
    currency CHAR(3) NOT NULL DEFAULT 'BRL',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'CLOSED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE prize (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raffle_id BIGINT NOT NULL REFERENCES raffle (id),
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    image_url TEXT,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE raffle_number (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raffle_id BIGINT NOT NULL REFERENCES raffle (id),
    number_value SMALLINT NOT NULL CHECK (number_value BETWEEN 1 AND 100),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
        CHECK (status IN ('AVAILABLE', 'RESERVED', 'PAID')),
    UNIQUE (raffle_id, number_value)
);

INSERT INTO raffle (id, slug, title, description, unit_price_cents, status)
VALUES (
    1,
    'iracema',
    'Rifa da Escola Iracema',
    'Escolha seus números e concorra aos prêmios da escola.',
    NULL,
    'ACTIVE'
);

INSERT INTO raffle_number (raffle_id, number_value)
SELECT 1, number_value
FROM generate_series(1, 100) AS number_value;
